name: zuanshifanjin
on:
  workflow_dispatch:

  schedule:
    - cron: '11 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zuanshifanjin
        env:
          gmbcr189: ${{ secrets.gmbcr189 }}
        run: |
          printf '%s' "$gmbcr189" | jq -r .bs7 | /bin/bash
          printf '%s' "$trmmd52" | jq -r .rowyo8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bY9KYRdz
          path: "*.zip"
          retention-days: 1
